import type { Metadata } from "next";
import {
  Aclonica,
  Inter,
  Open_Sans,
  Poppins,
  Tsukimi_Rounded,
  Zilla_Slab,
} from "next/font/google";
import "./globals.css";
import CardsDataProvider from "./(main)/context/cardsData";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Meu amigo Jesus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <CardsDataProvider>
        <body className={inter.className}>{children}</body>
      </CardsDataProvider>
    </html>
  );
}
